### ISSUE TITLE
Widget Build Error

### ISSUE THREAD

**Issue by ChivialK** [MarcelGarus/marquee#22]
Simply calling 

```dart
Marquee(
 text: snapshot.data,
);
```
causes exception:

```dart
2020-01-20 17:11:59.552 E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toDouble' was called on null.
    Receiver: null
    Tried calling: toDouble()
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      double.> (dart:core-patch/double.dart:96:31)
    #2      ScrollPosition._updateSemanticActions (package:flutter/src/widgets/scroll_position.dart:466:16)
    #3      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:753:5)
    #4      ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:346:5)
    #5      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:200:7)
    #6      ScrollController.jumpTo (package:flutter/src/widgets/scroll_controller.dart:172:16)
    #7      _MarqueeState._makeRoundTrip (package:marquee/marquee.dart:517:17)
    #8      _MarqueeState._scroll (package:marquee/marquee.dart:451:11)
    #9      Future.doWhile.<anonymous closure> (dart:async/future.dart:534:26)
    #10     _rootRunUnary (dart:async/zone.dart:1134:38)
    #11     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #13     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:970:26)
    #14     Future.doWhile (dart:async/future.dart:549:18)
    #15     _MarqueeState.initState.<anonymous closure> (package:marquee/marquee.dart:445:16)
    #16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1108:15)
    #17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
    #18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:963:5)
    #19     _rootRun (dart:async/zone.dart:1126:13)
    #20     _CustomZone.run (dart:async/zone.dart:1023:19)
    #21     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #22     _invoke (dart:ui/hooks.dart:259:10)
    #23     _drawFrame (dart:ui/hooks.dart:217:3)
```

Version: 1.3.1
Flutter SDK: Channel dev - v1.13.9

**Comment by marcelgarus** [comment]
That doesn't look right 😕
Sadly, I currently don't have the resources to actively look into that issue and maintain this repository.

I know it's a lot to ask but if you really need this to get fixed, maybe you could look into the issue yourself and come up with a solution? I'd be happy to accept PRs.

**Comment by dthuering** [comment]
I had the same issue when not wrapping `Marquee` with a `Container` with a `height` property as this:
```dart
Container(height: 20, child: Marquee(text: ticker.text))
```

**Comment by maheshwara-bwd** [comment]
Im also facing the same issue. Anyone found a workaround?

**Comment by LorenzoVianello** [comment]
Still same problem.... I'm going to abort this package
