### ISSUE TITLE
Doesn't work in web

### ISSUE THREAD

**Issue by TomerconDevelopers** [marcelgarus/marquee#33]
UnimplementedError

**Comment by marcelgarus** [comment]
Good catch. I'll try to look into it, but it's gonna take some time

**Comment by HardVeur** [comment]
Had the same problem and just want to add some error messages.

Debugger stops at /flutter/packages/flutter/lib/src/rendering/layer.dart in line 1856

Error from the chrome console:
```
dart.developer.postEvent Flutter.Error {"description":"Exception caught by scheduler library","type":"_FlutterErrorDetailsNode","allowWrap":false,"objectId":"inspector-36690","valueId":"inspector-36691","properties":[{"description":"The following UnimplementedError was thrown during a scheduler callback:","type":"ErrorDescription","showSeparator":false,"showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-36692","valueId":"inspector-36693","properties":[],"children":[],"defaultValue":"null","missingIfNull":false,"propertyType":"List<Object>","defaultLevel":"info"},{"description":"UnimplementedError","type":"ErrorSummary","showSeparator":false,"level":"summary","showName":false,"style":"flat","allowNameWrap":true,"objectId":"inspector-36694","valueId":"inspector-36695","properties":[],"children":[],"defaultValue":"null","missingIfNull":false,"propertyType":"List<Object>","defaultLevel":"summary"},{"description":"","type":"ErrorSpacer","name":"","showName":false,"style":"singleLine","allowNameWrap":true,"objectId":"inspector-36696","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null},{"description":null,"type":"DiagnosticsStackTrace","name":"When the exception was thrown, this was the stack","style":"flat","allowTruncate":true,"allowWrap":false,"objectId":"inspector-36697","valueId":"inspector-36698","properties":[{"description":"dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_","type":"DiagnosticsProperty<void>","name":"","showName":false,"style":"singleLine","allowWrap":false,"allowNameWrap":true,"objectId":"inspector-36699","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null},{"description":"lib/_engine/engine/surface/scene_builder.dart 234:5                           pushShaderMask","type":"DiagnosticsProperty<void>","name":"","showName":false,"style":"singleLine","allowWrap":false,"allowNameWrap":true,"objectId":"inspector-36700","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null},{"description":"packages/flutter/src/rendering/layer.dart 1856:26                             addToScene","type":"DiagnosticsProperty<void>","name":"","showName":false,"style":"singleLine","allowWrap":false,"allowNameWrap":true,"objectId":"inspector-36701","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null},{"description":"packages/flutter/src/rendering/layer.dart 443:5                               [_addToSceneWithRetainedRendering]","type":"DiagnosticsProperty<void>","name":"","showName":false,"style":"singleLine","allowWrap":false,"allowNameWrap":true,"objectId":"inspector-36702","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null},{"description":"packages/flutter/src/rendering/layer.dart 1066:14                             addChildrenToScene","type":"DiagnosticsProperty<void>","name":"","showName":false,"style":"singleLine","allowWrap":false,"allowNameWrap":true,"objectId":"inspector-36703","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null},{"description":"...","type":"DiagnosticsProperty<void>","name":"","showName":false,"style":"singleLine","allowNameWrap":true,"objectId":"inspector-36704","valueId":null,"properties":[],"children":[],"missingIfNull":false,"propertyType":"void","defaultLevel":"info","value":null,"truncated":true}],"children":[]}],"children":[],"errorsSinceReload":2446}
```
The stack at this point:

```
"Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:49982/dart_sdk.js:4463:11)
    at _engine.SurfaceSceneBuilder.new.pushShaderMask (http://localhost:49982/dart_sdk.js:156906:17)
    at layer$.ShaderMaskLayer.new.addToScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:2006:34)
    at layer$.ShaderMaskLayer.new.[_addToSceneWithRetainedRendering] (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:733:12)
    at layer$.PhysicalModelLayer.new.addChildrenToScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:1318:50)
    at layer$.PhysicalModelLayer.new.addToScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:2168:12)
    at layer$.PhysicalModelLayer.new.[_addToSceneWithRetainedRendering] (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:733:12)
    at layer$.OffsetLayer.new.addChildrenToScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:1318:50)
    at layer$.OffsetLayer.new.addToScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:1415:12)
    at layer$.OffsetLayer.new.[_addToSceneWithRetainedRendering] (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:733:12)
    at layer$.OffsetLayer.new.addChildrenToScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:1318:50)
    at layer$.OffsetLayer.new.addToScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:1415:12)
    at layer$.OffsetLayer.new.[_addToSceneWithRetainedRendering] (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:733:12)
    at layer$.TransformLayer.new.addChildrenToScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:1318:50)
    at layer$.TransformLayer.new.addToScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:1832:12)
    at layer$.TransformLayer.new.buildScene (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:1121:12)
    at view.RenderView.new.compositeFrame (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:4355:32)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:5382:25)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:49982/packages/flutter/src/widgets/widget_span.dart.lib.js:42578:15)
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:49982/packages/flutter/src/rendering/layer.dart.lib.js:5358:12)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:49982/packages/flutter/src/scheduler/binding.dart.lib.js:726:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:49982/packages/flutter/src/scheduler/binding.dart.lib.js:698:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:49982/packages/flutter/src/scheduler/binding.dart.lib.js:655:12)
    at Object._invoke (http://localhost:49982/dart_sdk.js:167693:7)
    at _engine.EngineWindow.new.invokeOnDrawFrame (http://localhost:49982/dart_sdk.js:164641:15)
    at http://localhost:49982/dart_sdk.js:165156:28"
```

**Comment by marcelgarus** [comment]
I'm currently quite busy with studying and work stuff, so it's probably gonna take some time before I find time to look at it. If anyone has spare time and feels like it, don't hesitate to code something up and file a PR.

**Comment by AngusPei** [comment]
same here

**Comment by HardVeur** [comment]
We can close this issue for now.

**Comment by Appwrite-Guru** [comment]
Was it fixed? I can use this package locally but it dont work after deploy
