### ISSUE TITLE
The getter 'visible' was called on null

### ISSUE THREAD

**Issue by wednesday** [marcelgarus/marquee#38]
```
Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      double.>  (dart:core-patch/double.dart:94:31)
#2      ScrollPosition._updateSemanticActions 
package:flutter/…/widgets/scroll_position.dart:472
#3      ScrollPosition.notifyListeners 
package:flutter/…/widgets/scroll_position.dart:809
#4      ScrollPosition.forcePixels 
package:flutter/…/widgets/scroll_position.dart:346
#5      ScrollPositionWithSingleContext.jumpTo 
package:flutter/…/widgets/scroll_position_with_single_context.dart:202
#6      ScrollController.jumpTo 
package:flutter/…/widgets/scroll_controller.dart:178
#7      _MarqueeState._makeRoundTrip 
package:marquee/marquee.dart:602
#8      _MarqueeState._scroll 
package:marquee/marquee.dart:536
#9      Future.doWhile.<anonymous closure>  (dart:async/future.dart:550:26)
```

marquee version 1.5.3
```
variable!=null?Marquee(
          text: variable['name']
 ):null
```
flutter doctor -V
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.20.2 at /Users/as/Downloads/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/as/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • F6C7B0C9-8B02-4C25-98AD-5431C314D99B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
```

**Comment by marcelgarus** [comment]
There was an error with a disconnected `ScrollController`, which got fixed by a PR.
Does the error still occur?
